language: node_js
node_js:
  - 0.10
services:
  - docker

env: BROWSERS=firefox E2E_BROWSERS=Firefox

before_script:
  - docker build -t $DOCKER_USERNAME/angular-phonecat:$TRAVIS_BRANCH .
  - docker run -d -p 127.0.0.1:8000:8000 $DOCKER_USERNAME/angular-phonecat:$TRAVIS_BRANCH
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm run update-webdriver

script:
  - node_modules/.bin/karma start test/karma.conf.js --single-run
  - node_modules/.bin/protractor test/protractor-conf.js

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD -e $DOCKER_EMAIL
  - docker push $DOCKER_USERNAME/angular-phonecat:$TRAVIS_BRANCH

notifications:
  slack: kahara:JZK5i2aigUY1WJW0MDxuWSvA

notifications:
  webhooks: https://outlook.office365.com/webhook/2057372b-54ef-42ec-896e-7c698ca2e4bd@72f988bf-86f1-41af-91ab-2d7cd011db47/TravisCI/f70aaf26bb1345b3bca3633e42ecb0d1/bb67bd3b-9b3f-4337-9b69-4983f8b1f33c